# 发送本地文件到服务器
# 0,30 * * * * scp -P REMOTE_SERVER_SSH_PORT LOCAL_FILE USER@REMOTE_SERVER_IP:SOME_PATH

# 发送本地文件的最后1000行到服务器（增量）
# 0,15,30,45 * * * * tail -n 1000 LOCAL_FILE |ssh -p REMOTE_SERVER_SSH_PORT USER@REMOTE_SERVER_IP "cat > SOME_PATH"
